using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Globalization;
using System.IO;
using System.Reflection;
using System.Text;

namespace ScanLink.DesignSystem
{
    /// <summary>
    /// Lucide icons drawn as vectors, at any size and in any colour — the same icon set and
    /// the same names the mockup uses (<c>&lt;Icon name="cloud-upload" size={16} /&gt;</c> becomes
    /// <c>SLIcon.Draw(g, "cloud-upload", rect, color)</c>).
    ///
    /// Geometry comes from Assets/lucide-icons.txt (generated by design/tools/build-icons.js),
    /// parsed once per icon into a 24x24 GraphicsPath and stroked like the mockup's Icon.jsx:
    /// stroke-width 1.75 in viewBox units, round caps and joins.
    /// </summary>
    internal static class SLIcon
    {
        public const float DefaultStroke = 1.75f;

        private sealed class Glyph
        {
            public GraphicsPath Stroked;
            public GraphicsPath Filled;
        }

        private static Dictionary<string, string> _source;
        private static readonly Dictionary<string, Glyph> Glyphs = new Dictionary<string, Glyph>(StringComparer.Ordinal);
        private static readonly Dictionary<string, Bitmap> Bitmaps = new Dictionary<string, Bitmap>(StringComparer.Ordinal);
        private static readonly object Gate = new object();

        /// <summary>"cloud-upload" -> "CloudUpload", exactly as Icon.jsx converts names.</summary>
        public static string ToPascal(string name)
        {
            if (string.IsNullOrEmpty(name)) return name;
            StringBuilder sb = new StringBuilder(name.Length);
            foreach (string part in name.Split('-', '_', ' '))
            {
                if (part.Length == 0) continue;
                sb.Append(char.ToUpperInvariant(part[0]));
                sb.Append(part, 1, part.Length - 1);
            }
            return sb.ToString();
        }

        public static bool Exists(string name)
        {
            return Find(name) != null;
        }

        /// <summary>Strokes the icon inside rect (normally square: size x size).</summary>
        public static void Draw(Graphics g, string name, Rectangle rect, Color color)
        {
            Draw(g, name, rect, color, DefaultStroke);
        }

        public static void Draw(Graphics g, string name, Rectangle rect, Color color, float strokeWidth)
        {
            Glyph glyph = Find(name);
            if (glyph == null || rect.Width <= 0 || rect.Height <= 0) return;

            float scale = Math.Min(rect.Width, rect.Height) / 24f;
            float ox = rect.X + (rect.Width - 24f * scale) / 2f;
            float oy = rect.Y + (rect.Height - 24f * scale) / 2f;

            SmoothingMode oldSmoothing = g.SmoothingMode;
            PixelOffsetMode oldOffset = g.PixelOffsetMode;
            g.SmoothingMode = SmoothingMode.AntiAlias;
            g.PixelOffsetMode = PixelOffsetMode.HighQuality;
            try
            {
                using (Matrix m = new Matrix(scale, 0, 0, scale, ox, oy))
                {
                    if (glyph.Stroked != null)
                    {
                        using (GraphicsPath p = (GraphicsPath)glyph.Stroked.Clone())
                        using (Pen pen = new Pen(color, strokeWidth * scale))
                        {
                            pen.StartCap = LineCap.Round;
                            pen.EndCap = LineCap.Round;
                            pen.LineJoin = LineJoin.Round;
                            p.Transform(m);
                            g.DrawPath(pen, p);
                        }
                    }
                    if (glyph.Filled != null)
                    {
                        using (GraphicsPath p = (GraphicsPath)glyph.Filled.Clone())
                        using (SolidBrush b = new SolidBrush(color))
                        using (Pen pen = new Pen(color, strokeWidth * scale))
                        {
                            p.Transform(m);
                            g.FillPath(b, p);
                            g.DrawPath(pen, p);
                        }
                    }
                }
            }
            finally
            {
                g.SmoothingMode = oldSmoothing;
                g.PixelOffsetMode = oldOffset;
            }
        }

        /// <summary>
        /// Cached bitmap for places that need an Image (stock controls, grid cells). Prefer
        /// Draw inside SL* controls. Returns null if the icon name is unknown.
        /// </summary>
        public static Bitmap Bitmap(string name, int size, Color color)
        {
            if (Find(name) == null || size <= 0) return null;
            string key = name + "|" + size + "|" + color.ToArgb();
            lock (Gate)
            {
                Bitmap cached;
                if (Bitmaps.TryGetValue(key, out cached)) return cached;
                Bitmap bmp = new Bitmap(size, size, System.Drawing.Imaging.PixelFormat.Format32bppArgb);
                using (Graphics g = Graphics.FromImage(bmp))
                {
                    g.Clear(Color.Transparent);
                    Draw(g, name, new Rectangle(0, 0, size, size), color);
                }
                Bitmaps[key] = bmp;
                return bmp;
            }
        }

        private static Glyph Find(string name)
        {
            if (string.IsNullOrEmpty(name)) return null;
            string pascal = ToPascal(name);
            lock (Gate)
            {
                Glyph glyph;
                if (Glyphs.TryGetValue(pascal, out glyph)) return glyph;

                EnsureSource();
                string data;
                if (_source == null || !_source.TryGetValue(pascal, out data))
                {
                    Glyphs[pascal] = null;
                    System.Diagnostics.Debug.WriteLine("[SLIcon] unknown icon: " + name);
                    return null;
                }

                glyph = new Glyph();
                foreach (string raw in data.Split('|'))
                {
                    if (raw.Length == 0) continue;
                    bool filled = raw[0] == '!';
                    string d = filled ? raw.Substring(1) : raw;
                    GraphicsPath target;
                    if (filled) { if (glyph.Filled == null) glyph.Filled = new GraphicsPath(); target = glyph.Filled; }
                    else { if (glyph.Stroked == null) glyph.Stroked = new GraphicsPath(); target = glyph.Stroked; }
                    try
                    {
                        SvgPath.AppendTo(target, d);
                    }
                    catch (Exception ex)
                    {
                        System.Diagnostics.Debug.WriteLine("[SLIcon] bad path in " + pascal + ": " + ex.Message);
                    }
                }
                Glyphs[pascal] = glyph;
                return glyph;
            }
        }

        private static void EnsureSource()
        {
            if (_source != null) return;
            _source = new Dictionary<string, string>(StringComparer.Ordinal);
            try
            {
                Assembly asm = Assembly.GetExecutingAssembly();
                string resource = null;
                foreach (string r in asm.GetManifestResourceNames())
                {
                    if (r.EndsWith("lucide-icons.txt", StringComparison.OrdinalIgnoreCase)) { resource = r; break; }
                }
                if (resource == null) return;
                using (Stream s = asm.GetManifestResourceStream(resource))
                using (StreamReader reader = new StreamReader(s, Encoding.UTF8))
                {
                    string line;
                    while ((line = reader.ReadLine()) != null)
                    {
                        if (line.Length == 0 || line[0] == '#') continue;
                        int tab = line.IndexOf('\t');
                        if (tab <= 0) continue;
                        _source[line.Substring(0, tab)] = line.Substring(tab + 1);
                    }
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine("[SLIcon] could not load icon data: " + ex.Message);
            }
        }
    }
}
