// Generates ScanLink/Assets/lucide-icons.txt from the Lucide build inside the mockup.
//
//   node design/tools/unpack-mockup.js   (once)
//   node design/tools/build-icons.js
//
// The mockup draws every icon with Lucide. WinForms has no SVG support, so instead of baking
// PNGs per size and colour, each icon is reduced to plain SVG path strings that SLIcon.cs
// strokes with GDI+ at any size and in any colour.
//
// Output, one icon per line:   <PascalName>\t<path>|<path>|...
// Names stay PascalCase; SLIcon converts "cloud-upload" -> "CloudUpload" exactly as the
// mockup's Icon.jsx does, so any icon name used in the mockup resolves identically.
// A path prefixed with "!" is filled rather than stroked (a handful of icons have solid dots).
'use strict';
const fs = require('fs');
const path = require('path');

const LUCIDE = path.join(__dirname, '..', 'mockup', 'vendor', 'lucide.js');
const OUT = path.join(__dirname, '..', '..', 'ScanLink', 'Assets', 'lucide-icons.txt');

const n = (v) => Number(v);
const f = (v) => +Number(v).toFixed(3);

function rectPath(a) {
  const x = n(a.x || 0), y = n(a.y || 0), w = n(a.width), h = n(a.height);
  let rx = a.rx != null ? n(a.rx) : a.ry != null ? n(a.ry) : 0;
  let ry = a.ry != null ? n(a.ry) : rx;
  rx = Math.min(rx, w / 2); ry = Math.min(ry, h / 2);
  if (!rx || !ry) return `M${f(x)} ${f(y)}h${f(w)}v${f(h)}h${f(-w)}Z`;
  return `M${f(x + rx)} ${f(y)}h${f(w - 2 * rx)}a${f(rx)} ${f(ry)} 0 0 1 ${f(rx)} ${f(ry)}` +
    `v${f(h - 2 * ry)}a${f(rx)} ${f(ry)} 0 0 1 ${f(-rx)} ${f(ry)}h${f(-(w - 2 * rx))}` +
    `a${f(rx)} ${f(ry)} 0 0 1 ${f(-rx)} ${f(-ry)}v${f(-(h - 2 * ry))}a${f(rx)} ${f(ry)} 0 0 1 ${f(rx)} ${f(-ry)}Z`;
}

function ellipsePath(cx, cy, rx, ry) {
  return `M${f(cx - rx)} ${f(cy)}a${f(rx)} ${f(ry)} 0 1 0 ${f(2 * rx)} 0a${f(rx)} ${f(ry)} 0 1 0 ${f(-2 * rx)} 0Z`;
}

function pointsPath(points, close) {
  const nums = String(points).trim().split(/[\s,]+/).map(n);
  let d = '';
  for (let i = 0; i < nums.length; i += 2) d += (i === 0 ? 'M' : 'L') + f(nums[i]) + ' ' + f(nums[i + 1]);
  return close ? d + 'Z' : d;
}

function toPath(tag, a) {
  switch (tag) {
    case 'path': return a.d;
    case 'rect': return rectPath(a);
    case 'circle': return ellipsePath(n(a.cx), n(a.cy), n(a.r), n(a.r));
    case 'ellipse': return ellipsePath(n(a.cx), n(a.cy), n(a.rx), n(a.ry));
    case 'line': return `M${f(a.x1)} ${f(a.y1)}L${f(a.x2)} ${f(a.y2)}`;
    case 'polyline': return pointsPath(a.points, false);
    case 'polygon': return pointsPath(a.points, true);
    default: throw new Error('unsupported element ' + tag);
  }
}

function main() {
  const lucide = require(LUCIDE);
  const lines = [];
  for (const name of Object.keys(lucide.icons).sort()) {
    const node = lucide.icons[name];
    const list = Array.isArray(node[2]) ? node[2] : node;
    const paths = list.map(([tag, attrs]) => {
      const filled = attrs.fill && attrs.fill !== 'none';
      return (filled ? '!' : '') + toPath(tag, attrs).replace(/\s+/g, ' ').trim();
    });
    lines.push(name + '\t' + paths.join('|'));
  }
  fs.writeFileSync(OUT, '# Lucide v0.460.0 (ISC). Generated by design/tools/build-icons.js; do not edit.\n' + lines.join('\n') + '\n');
  console.log('wrote', lines.length, 'icons to', path.relative(process.cwd(), OUT));
}

main();
